from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence


def q(
    prompt: str,
    correct: str,
    distractors: Sequence[str],
    explanation: str,
    review_terms: Sequence[str],
    *,
    use_image: bool = False,
    image_review_terms: Optional[Sequence[str]] = None,
    image_source: Optional[str] = None,
    image_page: Optional[int] = None,
    image_caption: Optional[str] = None,
) -> Dict[str, Any]:
    return {
        "prompt": prompt,
        "correct": correct,
        "distractors": list(distractors),
        "explanation": explanation,
        "review_terms": list(review_terms),
        "use_image": bool(use_image),
        "image_review_terms": list(image_review_terms or []),
        "image_source": str(image_source or "").strip(),
        "image_page": int(image_page or 0),
        "image_caption": str(image_caption or "").strip(),
    }


def img_q(
    prompt: str,
    correct: str,
    distractors: Sequence[str],
    explanation: str,
    review_terms: Sequence[str],
    image_review_terms: Optional[Sequence[str]] = None,
    *,
    image_source: Optional[str] = None,
    image_page: Optional[int] = None,
    image_caption: Optional[str] = None,
) -> Dict[str, Any]:
    return q(
        prompt,
        correct,
        distractors,
        explanation,
        review_terms,
        use_image=True,
        image_review_terms=image_review_terms,
        image_source=image_source,
        image_page=image_page,
        image_caption=image_caption,
    )


QUESTION_BLUEPRINTS: Dict[str, List[Dict[str, Any]]] = {
    "深度学习概述": [
        q(
            "与传统机器学习相比，深度学习在特征处理上的核心特点是什么？",
            "模型不仅学习分类边界，还从原始数据中自动学习有用的特征表示。",
            [
                "先由人工把特征设计好，模型只负责最后的分类决策。",
                "模型只要记住训练样本即可，不需要形成可迁移的内部表示。",
                "网络一旦变深，就可以不再关心特征是如何形成的。",
            ],
            "深度学习的重要特点是表示学习，即模型不仅完成分类，还能从原始数据中自动学习分层特征。",
            ["representation learning", "deep learning", "feature learning"],
        ),
        q(
            "如果图像分类流程不再手工设计 HOG / SIFT，而是让模型直接从像素学到类别，应该优先考虑哪类方案？",
            "端到端的深度学习方法。",
            [
                "先固定手工特征，再配一个浅层分类器。",
                "把任务完全改写成人工规则驱动的专家系统。",
                "只保留随机特征映射，再交给最近邻或查表方法处理。",
            ],
            "深度学习的重要优势之一，就是能够从原始数据中逐层学习任务相关表示。",
            ["deep learning", "end-to-end", "representation learning"],
        ),
        q(
            "关于人工智能、机器学习和深度学习的层级关系，下列说法哪一项正确？",
            "深度学习属于机器学习的重要分支，而机器学习又是人工智能的重要实现路径之一。",
            [
                "人工智能是深度学习中的一个小分支。",
                "机器学习和深度学习本质上是同一个概念，只是叫法不同。",
                "深度学习与人工智能彼此独立，只是研究者习惯放在一起讨论。",
            ],
            "课程通常用包含关系来说明三者层级：AI 范围最大，ML 是其中方法，DL 是 ML 的重要分支。",
            ["artificial intelligence", "machine learning", "deep learning"],
        ),
        q(
            "关于“把网络做深”的含义，下列说法正确的是？",
            "通过更多层非线性变换，逐步形成更抽象、更任务相关的表示。",
            [
                "只是把每一层做得更宽、参数更多，而层间功能不变。",
                "简单重复同一个线性映射，不再引入新的非线性表达。",
                "保持网络结构不变，只把训练轮数拉长。",
            ],
            "“深”首先强调的是层次化表示和多层非线性映射，而不是单纯参数量或训练时长。",
            ["deep network", "hierarchical representation", "nonlinear transformation"],
        ),
        img_q(
            "根据图中 2012 年与后续竞赛节点的描述，哪项最能解释 AlexNet 为什么常被视为视觉深度学习竞赛时代的起点？",
            "它先把 ImageNet 错误率由 26% 降到 15% 并夺冠，随后图中又列出 VGG、GoogleNet、ResNet、SENet 持续刷新结果，说明 AlexNet 打开了后续架构竞赛式迭代的起点。",
            [
                "它直接把错误率降到 2.25%，并在同一年结束了 ImageNet 比赛。",
                "它并未参与图像识别竞赛，图中真正的转折点其实是 2012 年的语音识别结果。",
                "它之后没有出现新的视觉网络，图中的发展脉络在 2012 年已经结束。",
            ],
            "要答对这题，必须同时利用图中 AlexNet 的成绩和后续网络持续压低错误率这两层信息，而不是只记住单个年份。",
            ["deep learning", "alexnet", "imagenet", "发展"],
            ["deep learning", "alexnet", "imagenet"],
            image_source="Week1/0.1-DeepLearning-Introduction-C1.pdf",
            image_page=21,
            image_caption="0.1-DeepLearning-Introduction-C1.pdf 第 21 页",
        ),
        img_q(
            "图中先并列给出 2012 年语音识别突破与 AlexNet，随后又连续列出 VGG、GoogleNet、ResNet、SENet。仅依据这一排布，后续发展主线更接近哪一项？",
            "以 ImageNet 为牵引的视觉网络架构持续迭代，而不是停留在单一语音识别突破上。",
            [
                "以 GMM/HMM 之类传统语音模型的小修小补为主线。",
                "以 2018 年停办比赛为主线，因此后续网络发展不再重要。",
                "以彻底脱离基准测试为主线，因此后续模型不再比较错误率。",
            ],
            "这题要看图中的事件排布方式，而不是只看某一句文字。前面是两个 2012 年突破，后面却几乎全是视觉竞赛网络，说明课程叙事的主轴已经转向视觉架构演进。",
            ["deep learning", "alexnet", "imagenet", "发展"],
            ["deep learning", "alexnet", "imagenet"],
            image_source="Week1/0.1-DeepLearning-Introduction-C1.pdf",
            image_page=21,
            image_caption="0.1-DeepLearning-Introduction-C1.pdf 第 21 页",
        ),
    ],
    "数学基础与机器学习基础": [
        q(
            "在监督学习里，如果没有损失函数，训练阶段最直接会缺少什么？",
            "度量模型预测与真实标签之间的差距，并据此指导参数更新。",
            [
                "缺少网络结构定义，因此模型无法前向计算。",
                "缺少数据预处理步骤，因此样本不能输入模型。",
                "缺少可视化曲线，因此无法观察训练过程。",
            ],
            "损失函数是训练时被优化的目标，作用是把“预测得有多差”量化出来。",
            ["loss function", "optimization", "supervised learning"],
        ),
        q(
            "用梯度下降最小化目标函数时，参数更新的基本方向是什么？",
            "沿着损失函数梯度的反方向更新。",
            [
                "沿梯度正方向更新，因为梯度本身就是最优下降方向。",
                "先固定更新方向，再只靠学习率去调损失大小。",
                "每一步只更新偏置，不更新权重，也能完成最小化。",
            ],
            "梯度给出局部上升最快方向；要做最小化，就应沿其反方向移动。",
            ["gradient descent", "loss", "optimization"],
        ),
        q(
            "如果训练误差和测试误差都偏大，这种现象更像下面哪一种？",
            "模型表达能力不足或训练不充分，属于欠拟合倾向。",
            [
                "典型过拟合，因为测试集一差就说明模型太复杂。",
                "主要是测试集出了问题，模型本身通常没有明显缺陷。",
                "说明模型已经接近最优，只需要继续保持当前设置。",
            ],
            "训练和测试都差，通常先看欠拟合，而不是一开始就判断成过拟合。",
            ["underfitting", "bias", "training error", "test error"],
        ),
        q(
            "在监督学习中，标签之所以重要，核心原因是什么？",
            "为模型提供明确的学习目标，使误差能够被计算并反向用于更新参数。",
            [
                "它主要用于测试阶段展示结果，对训练过程不产生作用。",
                "它只是决定 batch 的组织方式，不直接进入目标函数。",
                "它的作用主要是帮助打乱样本顺序，而不是定义学习目标。",
            ],
            "没有标签，监督学习就无法形成“预测值和目标值之间的误差”这一核心信号。",
            ["label", "supervised learning", "loss function"],
        ),
        img_q(
            "根据图中的噪声假设 Y=f(X)+ε 和误差分解式，若 Bias^2 与 Var 都已较小，测试误差仍存在稳定下界，最合理的解释是？",
            "由 ε 引出的不可约噪声项 sigma_e^2 仍保留在误差分解中，这部分误差不是继续调模型复杂度就能消掉的。",
            [
                "训练误差会作为独立项永久保留在泛化误差分解式中。",
                "学习率本身就是测试误差分解的一部分，因此下界主要由学习率决定。",
                "只要正则化足够强，误差分解中的剩余项就一定会消失。",
            ],
            "这题要同时看图中的噪声假设和下方展开式。Bias^2 与 Var 之外，sigma_e^2 才是误差下界的来源。",
            ["bias variance", "泛化误差", "误差分析"],
            ["bias", "variance", "误差分析"],
            image_source="Week2/0.2-DeepLearning-Foundations-C2.pdf",
            image_page=53,
            image_caption="0.2-DeepLearning-Foundations-C2.pdf 第 53 页",
        ),
        img_q(
            "某同学认为“只要继续把网络做深，泛化误差最终一定可以逼近 0”。结合图中的分解式，这一说法最直接忽略了什么？",
            "忽略了由数据噪声带来的不可约误差项；即使模型更复杂，也不意味着这部分下界会消失。",
            [
                "忽略了训练误差始终会单独出现在泛化误差公式中。",
                "忽略了学习率本身就是误差分解中的决定性项。",
                "忽略了只要正则化系数足够大，误差的各项都会同时变成 0。",
            ],
            "正确答案必须同时用到图里的噪声假设和展开式。公式已经明确说明：误差下界不只由 Bias 和 Var 决定。",
            ["bias variance", "泛化误差", "误差分析"],
            ["bias", "variance", "误差分析"],
            image_source="Week2/0.2-DeepLearning-Foundations-C2.pdf",
            image_page=53,
            image_caption="0.2-DeepLearning-Foundations-C2.pdf 第 53 页",
        ),
    ],
    "神经元、感知器与反向传播": [
        q(
            "单层感知器最适合直接处理哪类二分类问题？",
            "线性可分的分类问题。",
            [
                "像 XOR 这类明显非线性可分的问题。",
                "需要长期记忆和门控机制的序列建模问题。",
                "依赖自注意力来整合全局上下文的信息建模问题。",
            ],
            "感知器的判别边界本质上是线性的，因此适合线性可分任务。",
            ["perceptron", "linear separable", "classifier"],
        ),
        q(
            "多层感知器里如果去掉激活函数，首先失去的是什么能力？",
            "为网络引入非线性，使多层堆叠具备更强表达能力。",
            [
                "参数共享能力，因此每一层将无法复用特征。",
                "把输入转换成概率分布的能力，因此网络无法训练。",
                "损失函数的定义能力，因此网络不再需要优化目标。",
            ],
            "如果没有非线性激活，多层线性层叠加后仍可等价成一个线性变换。",
            ["activation function", "nonlinearity", "mlp"],
        ),
        q(
            "反向传播把输出误差一层层传回去，本质上反复用到哪条求导规则？",
            "链式法则。",
            [
                "贝叶斯公式。",
                "独立同分布假设。",
                "主成分分析中的特征分解。",
            ],
            "反向传播本质上就是借助链式法则，把复合函数的梯度逐层拆开计算。",
            ["backpropagation", "chain rule", "gradient"],
        ),
        q(
            "如果某个激活函数在大范围输入上梯度都接近 0，深层训练最常见的后果是什么？",
            "梯度在反向传播过程中不断衰减，前层难以有效更新。",
            [
                "学习率会自动等效放大，因此训练更快收敛。",
                "前面层会自动学到长期记忆，不再需要门控结构。",
                "网络会自动把前馈结构改写成循环结构。",
            ],
            "局部导数过小会在链式相乘时导致梯度消失，这是深层网络训练中的典型问题。",
            ["vanishing gradient", "activation function", "backpropagation"],
        ),
        img_q(
            "根据图中“阶跃函数 → Sigmoid”的替换关系，BP 训练真正需要修复的是阶跃函数的哪一缺陷？",
            "不是它只能输出 0/1，而是它不连续、不可导，导致误差难以按链式法则稳定回传。",
            [
                "阶跃函数无法输出负值，因此网络不能做二分类。",
                "阶跃函数会破坏卷积层的参数共享，所以 CNN 无法训练。",
                "阶跃函数会让输出层自动失去类别概率解释，因此 softmax 无法定义。",
            ],
            "图里把阶跃函数和 Sigmoid 并列，不是让学生背名字，而是让学生判断：为了让 BP 成立，被替换掉的是“不可导”这一训练瓶颈。",
            ["backpropagation", "sigmoid", "activation function"],
            ["backpropagation", "sigmoid", "activation function"],
            image_source="Week3/0.2-DeepLearning-Foundations-C3.pdf",
            image_page=17,
            image_caption="0.2-DeepLearning-Foundations-C3.pdf 第 17 页",
        ),
        img_q(
            "若仍希望输出层表达“接近 0/1”的二值倾向，图中为什么训练阶段也不回到阶跃函数？",
            "因为训练阶段首先需要可用于求导的激活函数；是否接近二值输出是次要的，能否稳定回传梯度才是前提。",
            [
                "因为阶跃函数会让卷积层失去参数共享，所以网络规模会立刻失控。",
                "因为阶跃函数只能用于无监督学习，不能用于有标签任务。",
                "因为阶跃函数会自动取消损失函数，所以训练目标无法定义。",
            ],
            "这题不能只凭常识去答，需要利用图中“阶跃函数不可导、Sigmoid 可导”的对照关系来判断训练优先级。",
            ["backpropagation", "sigmoid", "activation function"],
            ["backpropagation", "sigmoid", "activation function"],
            image_source="Week3/0.2-DeepLearning-Foundations-C3.pdf",
            image_page=17,
            image_caption="0.2-DeepLearning-Foundations-C3.pdf 第 17 页",
        ),
    ],
    "卷积神经网络基础": [
        q(
            "和全连接层相比，卷积层最能体现 CNN 图像建模特点的两个结构设定是什么？",
            "局部连接和参数共享。",
            [
                "每个输出单元都连接整幅输入，并且每个位置都使用独立参数。",
                "主要依靠池化完成特征提取，卷积核本身不是关键。",
                "不同空间位置必须学习完全不同的卷积参数，不能共享。",
            ],
            "CNN 适合图像数据的重要原因之一，就是局部连接保留空间结构，参数共享降低参数规模。",
            ["convolution", "local connectivity", "weight sharing"],
        ),
        q(
            "在 CNN 中插入池化层，通常是为了什么？",
            "在保留主要响应的同时降低特征图尺寸，并增强一定的平移鲁棒性。",
            [
                "让每一个卷积核都被全连接层替代，便于统一建模。",
                "把所有特征压成一个类别标签，提前结束后续计算。",
                "显著增加参数量和存储量，以提升模型记忆训练集的能力。",
            ],
            "池化层常被视为一种下采样操作，用来压缩表示并保留较显著特征。",
            ["pooling", "downsampling", "feature map"],
        ),
        q(
            "随着网络加深，某一层单元的感受野变大，通常说明什么？",
            "该层单元能整合更大输入区域中的上下文信息。",
            [
                "该层反而只能看到更少的像素，因此更适合局部去噪。",
                "感受野越大，模型参数就一定越少。",
                "感受野大小主要由类别数决定，与卷积结构关系不大。",
            ],
            "感受野描述的是某个单元在原始输入上能够“看到”的区域范围，是理解 CNN 的关键概念。",
            ["receptive field", "cnn", "context"],
        ),
        img_q(
            "根据图中 CNN 基本结构的排列顺序，若把全连接层放到卷积/池化之前，最先破坏的是哪一设计逻辑？",
            "模型还没有完成从局部模式到高层表示的逐层抽取，就过早进入全局判定。",
            [
                "卷积核将不再能够共享参数，因此卷积运算本身会失效。",
                "池化层将无法降低分辨率，因此特征图尺寸不会发生变化。",
                "激活函数将不再提供非线性，因此所有层都会退化成恒等映射。",
            ],
            "题目要利用图中的模块顺序来判断。该页体现的是“先提特征、后做判定”的结构逻辑，而不是把各层随意互换。",
            ["cnn architecture", "convolution", "pooling", "output"],
            ["cnn", "convolution", "pooling"],
            image_source="Week3/0.3-DeepLearing-CNN-C3.pdf",
            image_page=10,
            image_caption="0.3-DeepLearing-CNN-C3.pdf 第 10 页",
        ),
        img_q(
            "根据图中的感受野连线，若两类样本局部纹理相似、只有更大范围上下文不同，最容易误判的是哪类单元？",
            "感受野较小的浅层单元，因为它们覆盖的输入区域不足以区分更大范围的上下文差异。",
            [
                "感受野最大的高层单元，因为它们会自动丢掉所有局部纹理信息。",
                "任意层都一样，因为图中每个特征点都默认对应整幅输入图像。",
                "只要卷积核大小固定，感受野大小就不会影响最终分类判断。",
            ],
            "答这题必须利用图中的映射关系来判断：哪类节点只“看到”局部区域，哪类节点才有条件利用更大的上下文。",
            ["receptive field", "feature map", "cnn"],
            ["receptive field", "feature map"],
            image_source="Week3/0.3-DeepLearing-CNN-C3.pdf",
            image_page=27,
            image_caption="0.3-DeepLearing-CNN-C3.pdf 第 27 页",
        ),
        img_q(
            "若图中某个特征点只对应输入中的很小局部区域，那么把它直接当作“整幅图像类别证据”最可能出现什么问题？",
            "该点看到的信息范围过窄，可能只反映局部纹理而不足以支撑整幅图像层面的类别判断。",
            [
                "该点会自动拥有整幅图像的全局语义，因此分类反而最稳定。",
                "该点会失去所有像素信息，因此既不能表示局部也不能表示全局。",
                "只要卷积核共享参数，单个点就等价于整张 feature map 的判断结果。",
            ],
            "这题必须依赖图中的映射关系。特征点和输入区域是一对多层级关系，不能把局部响应直接误当成全局判定。",
            ["receptive field", "feature map", "cnn"],
            ["receptive field", "feature map"],
            image_source="Week3/0.3-DeepLearing-CNN-C3.pdf",
            image_page=27,
            image_caption="0.3-DeepLearing-CNN-C3.pdf 第 27 页",
        ),
    ],
    "典型卷积网络与视觉应用": [
        q(
            "ResNet 引入残差连接，最主要是为了解决什么训练痛点？",
            "缓解深层网络训练困难，使信息和梯度更容易跨层传播。",
            [
                "把图像网络改造成循环网络，以便处理长序列。",
                "彻底取消非线性层，让深层网络退化成纯线性模型。",
                "减少对数据的依赖，让模型主要依靠人工特征工作。",
            ],
            "残差连接最核心的价值，是让很深的网络更容易优化，而不是简单“多加一条边”。",
            ["resnet", "residual connection", "deep network optimization"],
        ),
        q(
            "VGG 系列网络最有代表性的结构思路是什么？",
            "倾向于重复堆叠较小卷积核，通过更深层数提升表达能力。",
            [
                "主要依赖大卷积核的浅层结构，而不追求网络加深。",
                "把跳跃连接作为骨干设计核心，重点解决超深训练问题。",
                "大幅削弱卷积层作用，只保留池化和分类模块。",
            ],
            "VGG 的代表性思路，是用简单规则的小卷积核重复堆叠，构造更深的网络。",
            ["vgg", "small convolution kernel", "deep cnn"],
        ),
        q(
            "LeNet 最常被视为哪类经典任务的代表网络？",
            "早期手写数字识别等基础视觉分类任务。",
            [
                "大规模语言模型的自回归文本生成任务。",
                "基于自注意力的机器翻译或长文本建模任务。",
                "扩散模型中的逐步去噪采样任务。",
            ],
            "LeNet 是经典 CNN 入门网络，最常见的应用示例就是手写数字识别。",
            ["lenet", "digit recognition", "cnn history"],
        ),
        img_q(
            "图中同时给出 ILSVRC 2015 冠军和 CVPR 2016 Best Paper。仅依据这两类信息，哪项对 ResNet 价值的概括最准确？",
            "它不仅取得了基准结果上的领先，而且对应的方法创新足以改变“网络能否继续加深”这一训练范式。",
            [
                "它的贡献主要是把所有卷积核统一成 3×3，因此结构更整齐。",
                "它的核心价值在于把循环门控机制首次引入图像分类网络。",
                "它说明人工特征重新优于端到端学习，因此竞赛成绩才会提高。",
            ],
            "图里既有竞赛结果，也有顶会奖项。正确判断要把“效果领先”和“方法影响力大”这两层信息一起读出来。",
            ["resnet", "imagenet", "ilsvrc 2015"],
            ["resnet", "imagenet", "ilsvrc"],
            image_source="Week4/0.3-DeepLearing-CNN-C4.pdf",
            image_page=36,
            image_caption="0.3-DeepLearing-CNN-C4.pdf 第 36 页",
        ),
        img_q(
            "根据图中的 3×3 same 卷积和 2×2 池化设置，VGG 的设计思路更接近哪一项？",
            "用多层小卷积逐步扩大有效感受野，并通过更深的堆叠增加非线性表达能力。",
            [
                "用单层大卷积一次覆盖大范围区域，因此网络不必继续加深。",
                "尽量去掉池化和分类头，只保留最前面的浅层卷积结构。",
                "把循环门控单元作为主干，卷积层只负责输入预处理。",
            ],
            "正确答案不能只抄图里的 3×3 和 2×2，而要根据这组配置判断 VGG 想解决的是“大卷积还是多层小卷积”的设计问题。",
            ["vgg", "3x3 convolution", "2x2 pooling"],
            ["vgg", "3x3", "2x2"],
            image_source="Week4/0.3-DeepLearing-CNN-C4.pdf",
            image_page=28,
            image_caption="0.3-DeepLearing-CNN-C4.pdf 第 28 页",
        ),
        img_q(
            "若把图中 VGG 的多层 3×3 卷积粗暴替换成单层大卷积核，最可能先失去哪一类结构优势？",
            "在保持规则化设计的同时，通过层数堆叠逐步增强非线性表达能力这一优势。",
            [
                "池化层对空间尺寸的压缩能力会完全消失，因为它依赖 3×3 卷积才能工作。",
                "ImageNet 竞赛结果会自动保持不变，因为卷积核大小不会影响表示方式。",
                "网络会自动转成残差结构，因此深层优化困难会被直接消除。",
            ],
            "图里给出的不是一串孤立参数，而是一种结构哲学。把多层小卷积换成单层大卷积，损失的不只是参数形式，更是分层表示方式。",
            ["vgg", "3x3 convolution", "2x2 pooling"],
            ["vgg", "3x3", "2x2"],
            image_source="Week4/0.3-DeepLearing-CNN-C4.pdf",
            image_page=28,
            image_caption="0.3-DeepLearing-CNN-C4.pdf 第 28 页",
        ),
    ],
    "循环神经网络与LSTM": [
        q(
            "RNN 能用于序列建模，关键不只是“循环”这个名字，而是什么？",
            "它在时间步之间传递隐藏状态，能够利用前后时刻的信息。",
            [
                "它把每个时间步都当成彼此独立的样本来处理。",
                "它只能处理长度固定为 1 的输入，因此更稳定。",
                "它主要依靠卷积核共享去建模时间依赖。",
            ],
            "RNN 的关键不在于“循环”这个名字，而在于隐藏状态把序列依赖串联起来。",
            ["rnn", "sequence modeling", "hidden state"],
        ),
        q(
            "LSTM 相比普通 RNN，结构上最关键的增强是什么？",
            "通过门控机制更稳定地保留和更新长期信息。",
            [
                "不再传递状态，只根据当前时刻输入独立做判断。",
                "直接把循环单元替换成卷积或随机森林集成。",
                "不改网络结构，只靠调大学习率来解决长期依赖问题。",
            ],
            "LSTM 的核心创新就是门控单元和记忆单元，用来缓解长期依赖难学的问题。",
            ["lstm", "gating mechanism", "long-term dependency"],
        ),
        q(
            "训练 RNN 时，先沿时间轴展开再做反向传播，这个过程通常叫什么？",
            "时间反向传播（BPTT）。",
            [
                "Teacher forcing。",
                "批量归一化。",
                "随机失活（Dropout）。",
            ],
            "BPTT 是把循环结构展开成时间上的深层计算图，再做反向传播。",
            ["bptt", "rnn", "backpropagation through time"],
        ),
        img_q(
            "若按图中的时间展开结构，把横向状态连接删去，仅保留每个时刻的输入到隐藏层映射，模型最接近哪种退化情形？",
            "各时刻近似独立处理，难以利用前文区分“当前输入相同但语义不同”的序列情况。",
            [
                "退化为共享卷积核的二维图像分类器，主要丢失空间局部性。",
                "退化为多头注意力模型，只能依赖 Query、Key、Value 的并行对齐。",
                "退化为池化网络，主要问题变成特征图尺寸无法压缩。",
            ],
            "这题必须利用图中的时间展开和横向状态连接来判断。删除这条递推链，损失的是跨时刻上下文，而不是别的结构性质。",
            ["rnn", "hidden state", "sequence modeling"],
            ["rnn", "hidden state"],
            image_source="Week6/0.4-DeepLearing-RNN-C6.pdf",
            image_page=30,
            image_caption="0.4-DeepLearing-RNN-C6.pdf 第 30 页",
        ),
        img_q(
            "根据图中的 forget gate 公式，若某一维旧记忆应被主动清空，则该维对应的 f_t 最应接近哪种状态？",
            "接近 0，使上一时刻单元状态在这一维被显著压低。",
            [
                "接近 1，使旧记忆在该维被完整保留下来。",
                "取任意较大的负值，使 softmax 输出更尖锐。",
                "保持与类别数相同的常数值，用于决定输出层标签。",
            ],
            "图中的公式说明 forget gate 直接控制旧状态保留多少。若要清空某维记忆，关键不是换输入，而是让该维的 f_t 接近 0。",
            ["lstm", "forget gate", "memory cell"],
            ["lstm", "forget gate", "memory cell"],
            image_source="Week6/0.4-DeepLearing-RNN-C6.pdf",
            image_page=37,
            image_caption="0.4-DeepLearing-RNN-C6.pdf 第 37 页",
        ),
        img_q(
            "若一个任务要求跨很多时间步保留某个关键信息，结合图中的 forget gate 机制，该信息对应维度的 f_t 序列更应呈现哪种趋势？",
            "在较长时间范围内持续接近 1，使旧记忆能够被长期保留下来。",
            [
                "在大多数时间步接近 0，这样才能不断强化长期依赖。",
                "在不同时间步随机取负值，从而让记忆自动通过 softmax 放大。",
                "始终等于类别数，这样记忆长度才能与输出维度对齐。",
            ],
            "这题不能脱离图里的门控公式来答。若要长期保留信息，forget gate 就不应频繁关闭对应维度。",
            ["lstm", "forget gate", "memory cell"],
            ["lstm", "forget gate", "memory cell"],
            image_source="Week6/0.4-DeepLearing-RNN-C6.pdf",
            image_page=37,
            image_caption="0.4-DeepLearing-RNN-C6.pdf 第 37 页",
        ),
    ],
    "注意力机制与Transformer": [
        q(
            "在自注意力里，Q、K、V 三者的分工更接近下面哪种说法？",
            "Query 用来发起匹配，Key 用来被匹配，Value 提供最终聚合的信息内容。",
            [
                "Q 决定训练轮数，K 决定学习率，V 决定 batch size。",
                "Q、K、V 只是名字不同，实际计算角色完全相同。",
                "真正参与注意力计算的只有 V，Q 和 K 主要用于可视化展示。",
            ],
            "理解 Q、K、V 的角色分工，是理解注意力机制的第一步。",
            ["self-attention", "query", "key", "value"],
        ),
        q(
            "如果 Transformer 完全不加入位置编码，最直接会遇到什么问题？",
            "模型难以区分同一组词在不同顺序下的差别。",
            [
                "模型会失去全部可训练参数，因此无法反向传播。",
                "模型会被迫把所有句子截断成长度为 1 的输入。",
                "模型会自动改写成树模型来补偿顺序信息的缺失。",
            ],
            "自注意力本身对顺序不敏感，因此需要额外的位置编码告诉模型“谁在前、谁在后”。",
            ["transformer", "positional encoding", "self-attention"],
        ),
        q(
            "多头注意力机制想带来的核心收益是什么？",
            "让模型能在不同子空间和不同关系模式上并行建模依赖。",
            [
                "让所有注意力头尽量学习同一种关系，以减少表达差异。",
                "把原本可并行的注意力过程改成严格串行扫描。",
                "让模型不再依赖反向传播也能自动学到表示。",
            ],
            "多头并不是为了“重复同一件事”，而是让模型从多个视角提取相关性。",
            ["multi-head attention", "transformer", "representation"],
        ),
        img_q(
            "按图中的三阶段流程，若第一阶段得到的相关性分值不经过第二阶段就直接去加权 Value，最可能出现的后果是？",
            "权重不再是可比较的归一化分配，不同位置的原始分值会直接主导加权结果。",
            [
                "Value 会被强制转换为 one-hot 编码，因此无法继续求和。",
                "Query 与 Key 会自动失去维度信息，导致模型无法前向计算。",
                "注意力机制会退化成卷积运算，因此是否归一化不再重要。",
            ],
            "这题要结合图里的三阶段结构来答。第二阶段的作用不是装饰，而是把原始打分变成真正可用于加权的权重分布。",
            ["self-attention", "query", "key", "value"],
            ["self-attention", "query", "key"],
            image_source="Week7/0.5-Transformer-C7.pdf",
            image_page=15,
            image_caption="0.5-Transformer-C7.pdf 第 15 页",
        ),
        img_q(
            "根据图中的公式位置关系，1/sqrt(d_k) 这一因子直接服务于哪一步的数值稳定性？",
            "服务于 softmax 前的点积打分，防止维度增大时分值过大而使 softmax 过早饱和。",
            [
                "服务于 Value 与输出向量的维度对齐，否则矩阵乘法无法定义。",
                "服务于序列长度归一化，否则输出 token 数会少于输入 token 数。",
                "服务于多头数量的平衡，否则不同注意力头无法并行计算。",
            ],
            "正确答案要同时读懂图里的公式顺序和缩放因子所在位置。它修正的是打分阶段的数值范围，而不是输出长度或头数。",
            ["transformer", "scaled dot-product attention", "d_k"],
            ["transformer", "attention", "d_k"],
            image_source="Week7/0.5-Transformer-C7.pdf",
            image_page=32,
            image_caption="0.5-Transformer-C7.pdf 第 32 页",
        ),
        img_q(
            "若按图中的三阶段流程，第二阶段输出的权重几乎变成均匀分布，那么第三阶段得到的 Attention Value 更接近哪种效果？",
            "更接近对各个 Value 做近似平均，而不是突出少数高度相关的位置。",
            [
                "更接近只保留单个最大 Value，因为均匀分布会自动退化成 one-hot。",
                "更接近卷积核滑动结果，因为注意力一旦均匀就会变成卷积。",
                "更接近把 Query 与 Key 重新拼接，因此 Value 不再参与结果生成。",
            ],
            "这道题必须依赖图中的三阶段含义。第二阶段给出的就是第三阶段的加权系数；若它近似均匀，最终结果自然接近平均汇聚。",
            ["self-attention", "query", "key", "value"],
            ["self-attention", "query", "key"],
            image_source="Week7/0.5-Transformer-C7.pdf",
            image_page=15,
            image_caption="0.5-Transformer-C7.pdf 第 15 页",
        ),
    ],
    "GPT、BERT与视觉Transformer": [
        q(
            "GPT 和 BERT 在预训练目标上的典型区别，下面哪一项说得更对？",
            "GPT 更偏自回归预测下一个 token，BERT 更偏基于上下文的掩码预测。",
            [
                "GPT 主要做图像建模，BERT 主要做语音建模。",
                "GPT 不依赖预训练，BERT 只能在测试阶段在线训练。",
                "二者训练目标本质相同，只是论文命名方式不同。",
            ],
            "课程里对 GPT / BERT 的比较，首先看的是训练目标和上下文利用方式。",
            ["gpt", "bert", "pretraining objective", "masked language model"],
        ),
        q(
            "如果一个任务非常依赖某个词左右两侧的上下文，哪类预训练思路通常更合适？",
            "以 BERT 为代表的双向上下文编码思路。",
            [
                "只看左侧历史、不显式结合右侧信息的单向生成思路。",
                "只看当前词本身、不整合上下文的浅层线性模型。",
                "完全不利用上下文表示、直接套用树模型投票。",
            ],
            "双向建模的关键优势，就是同时整合当前位置左右两侧的信息。",
            ["bert", "bidirectional context", "pretrained language model"],
        ),
        q(
            "Swin Transformer 在视觉任务中被强调的结构特点是什么？",
            "通过窗口化和层次化设计，在视觉场景中平衡建模能力与计算代价。",
            [
                "完全放弃注意力机制，改由循环门控单元承担主干。",
                "把所有 patch 先压成一个标量，再交给分类层处理。",
                "用 GAN 判别器直接替代编码器完成特征抽取。",
            ],
            "Swin 的代表性特点是局部窗口注意力和层次化表示，这使它更适合视觉任务。",
            ["swin transformer", "vision transformer", "window attention"],
        ),
        img_q(
            "根据图中“一个预训练模型扇出到多个任务”的布局，若把这些连线改成“每个任务各配一个独立模型”，最先被削弱的教学结论是？",
            "预训练得到的共享表示具有迁移性，同一个基础模型可以经微调服务多个下游任务。",
            [
                "预训练模型都必须先在图像数据上做监督学习，然后才能用于 NLP 任务。",
                "不同下游任务的标签空间完全相同，因此天然可以共用一个分类头。",
                "只要参数规模足够大，模型就不再需要任何任务相关的数据。",
            ],
            "这道题必须依赖图里的“一个模型对应多任务”布局。被强调的不是任务名称本身，而是共享表示的迁移能力。",
            ["gpt", "bert", "pretrained model"],
            ["gpt", "bert", "pretrained"],
            image_source="Week7/0.5-Transformer-C7.pdf",
            image_page=42,
            image_caption="0.5-Transformer-C7.pdf 第 42 页",
        ),
        img_q(
            "图中只给出“hierarchical”和“4-stage”。若据此判断它最适合哪类视觉需求，下列哪项最合理？",
            "需要多尺度表征的视觉任务，因为层级结构意味着特征会随阶段推进逐步汇聚更大范围的信息。",
            [
                "只适合固定长度文本建模，因为 4-stage 结构本质上等价于时间展开。",
                "只适合单尺度像素回归，因为层级结构会破坏高层语义信息。",
                "只适合完全无监督聚类，因为分阶段设计与分类、检测无关。",
            ],
            "这页信息其实很少，因此答题关键在于把“层级化、4-stage”翻译成具体的视觉建模含义，而不是死记数字。",
            ["swin transformer", "vision transformer", "stage"],
            ["swin transformer", "vision transformer"],
            image_source="Week7/0.5-Transformer-C7.pdf",
            image_page=86,
            image_caption="0.5-Transformer-C7.pdf 第 86 页",
        ),
        img_q(
            "若把图中 Swin Transformer 的层级式 4-stage 结构改成单阶段平铺表示，最难保持的能力是什么？",
            "逐阶段形成从局部细节到更大尺度语义的多层级视觉表征能力。",
            [
                "把时间步递推到下一时刻的循环记忆能力。",
                "通过遗忘门精确控制旧状态保留比例的能力。",
                "把所有类别映射到同一监督标签空间的能力。",
            ],
            "这题要利用图里唯一给出的关键信息：层级化和分阶段。去掉这两点，最先损失的就是多尺度表征。",
            ["swin transformer", "vision transformer", "stage"],
            ["swin transformer", "vision transformer"],
            image_source="Week7/0.5-Transformer-C7.pdf",
            image_page=86,
            image_caption="0.5-Transformer-C7.pdf 第 86 页",
        ),
    ],
    "GAN 对抗生成": [
        q(
            "关于 GAN 中生成器与判别器的关系，下列说法正确的是？",
            "生成器努力生成更逼真的样本，判别器努力区分真假，两者通过对抗共同推动性能提升。",
            [
                "两者各自训练各自的，不会通过目标函数相互影响。",
                "判别器负责生成样本，生成器负责判定真假。",
                "两者主要在测试阶段起作用，训练阶段并不形成对抗。",
            ],
            "GAN 的核心不是“有两个网络”这么简单，而是二者在目标上相互博弈。",
            ["gan", "generator", "discriminator", "adversarial training"],
        ),
        q(
            "如果 GAN 长期只能生成几种非常相似的样本，这通常对应什么问题？",
            "模式崩塌（mode collapse）。",
            [
                "梯度裁剪。",
                "梯度爆炸。",
                "标签平滑。",
            ],
            "模式崩塌指生成器缺乏多样性，总是输出相似样本，是 GAN 训练的经典难点之一。",
            ["mode collapse", "gan", "generator diversity"],
        ),
        q(
            "条件 GAN 和普通 GAN 的直接区别，最核心的是哪一点？",
            "条件 GAN 在生成或判别时额外利用类别、文本等条件信息。",
            [
                "条件 GAN 不再需要判别器，只保留生成器即可。",
                "条件 GAN 只能处理一维信号，不能用于图像任务。",
                "条件 GAN 训练时不再使用损失函数约束生成过程。",
            ],
            "引入条件的意义，是让生成过程能受控，而不是完全无条件地“随便生成”。",
            ["conditional gan", "gan", "conditioned generation"],
        ),
        img_q(
            "根据图中对动态平衡的定义，若训练末期判别器准确率长期接近 90%，更说明发生了哪种情况？",
            "系统尚未达到图中所说的平衡，生成分布与真实分布之间仍存在明显差距。",
            [
                "系统已经达到最理想平衡，只是判别器比随机猜测更稳定。",
                "生成器已经完全学到真实分布，因此判别器准确率自然应继续上升。",
                "判别器准确率越高越能说明 GAN 训练成功，90% 比 50% 更接近平衡。",
            ],
            "要答这题，必须用图中“平衡时生成分布接近真实分布、判别器约 50%”这一成对描述来反推 90% 代表什么。",
            ["gan", "training", "equilibrium"],
            ["gan", "training", "equilibrium"],
            image_source="Week8/0.6-GAN-C8.pdf",
            image_page=24,
            image_caption="0.6-GAN-C8.pdf 第 24 页",
        ),
        img_q(
            "根据图中样本的按行排布，若固定条件标签只更换随机噪声，理论上最应保持不变、允许变化的分别是什么？",
            "数字类别应保持不变，而具体书写风格、笔画粗细和局部形状可以变化。",
            [
                "数字类别和像素细节都应完全不变，否则说明条件标签失效。",
                "数字类别可以任意变化，只要同一行的灰度分布接近即可。",
                "只要卷积核共享不变，类别和风格都会随噪声一起随机改变。",
            ],
            "这道题必须依赖图中的排布方式来判断。图里同一行体现的是“类别约束不变”，但并不意味着样本外观被锁成完全一样。",
            ["conditional gan", "label", "controlled generation"],
            ["conditional gan", "cgan", "label"],
            image_source="Week8/0.6-GAN-C8.pdf",
            image_page=36,
            image_caption="0.6-GAN-C8.pdf 第 36 页",
        ),
        img_q(
            "若图中同一行在固定标签条件下生成出的样本几乎完全相同、只剩微小噪声差别，这更可能提示哪类问题？",
            "在该条件标签下生成多样性不足，模型可能出现了条件内的模式塌缩。",
            [
                "条件控制效果更强，因此生成器已经学会在每个标签下只产生唯一正确答案。",
                "说明随机噪声比条件标签更重要，所以类别约束已经完全失效。",
                "说明判别器准确率已经稳定在 50%，系统必然达到最优平衡。",
            ],
            "这题必须结合图中同一行多样本的排布来判断。条件生成不等于每个标签只输出一个模板，完全相同反而暴露多样性问题。",
            ["conditional gan", "label", "controlled generation"],
            ["conditional gan", "cgan", "label"],
            image_source="Week8/0.6-GAN-C8.pdf",
            image_page=36,
            image_caption="0.6-GAN-C8.pdf 第 36 页",
        ),
    ],
    "深度生成模型与扩散模型": [
        q(
            "自编码器最基础的训练目标是什么？",
            "把输入压缩到潜在表示后，再尽量重建出原始输入。",
            [
                "只负责判别样本真假，不需要重建输入。",
                "只学习类别标签，不关心输入本身的内容结构。",
                "完全依靠对抗训练生成样本，不需要编码器和解码器。",
            ],
            "自编码器最基础的目标是重建输入，借此学习压缩表示。",
            ["autoencoder", "encoder", "decoder", "reconstruction"],
        ),
        q(
            "扩散模型处理生成任务时，最有代表性的思路是什么？",
            "先逐步加噪，再学习反向去噪过程以恢复或生成样本。",
            [
                "先不断裁剪网络层数，再通过集成投票恢复样本。",
                "只做一次前向映射，不需要逐步噪声建模过程。",
                "先由判别器判断真假，再靠门控结构直接删除噪声。",
            ],
            "扩散模型之所以有效，很大程度上就在于把复杂生成问题改写成可学习的逐步去噪过程。",
            ["diffusion model", "noise", "denoising"],
        ),
        q(
            "RBM（受限玻尔兹曼机）在结构上的典型特点是什么？",
            "可见层与隐含层之间有连接，而同层节点之间通常不直接相连。",
            [
                "同一层内部必须是全连接的，这样才能形成受限结构。",
                "它主要依赖输出层与标签层之间的连接来学习表示。",
                "它本质上就是一个加入残差边的前馈网络模块。",
            ],
            "RBM 的“受限”就体现在层内不连、层间连的双层二分结构上。",
            ["rbm", "restricted boltzmann machine", "bipartite graph"],
        ),
        img_q(
            "根据图中的 x→encoder→z→decoder→x_hat 结构，若把 z 当作监督类别标签来用，整个模型会被误读成哪类任务？",
            "会把重构式表示学习误读成监督分类，从而忽略 z 作为压缩表示的作用。",
            [
                "会把条件生成误读成对抗训练，因为 z 会被当成真假判别分数。",
                "会把无监督聚类误读成随机森林投票，因为 z 会被当成树节点编号。",
                "会把序列到序列翻译误读成位置编码恢复，因为 z 会被当成时间步索引。",
            ],
            "这题必须利用图中的箭头链路来判断。z 夹在 encoder 和 decoder 中间，承担的是表示压缩与重构中介，而不是监督标签角色。",
            ["autoencoder", "encoder", "decoder", "latent representation"],
            ["autoencoder", "latent representation"],
            image_source="Week10/0.6-GenerativeModel-C10.pdf",
            image_page=65,
            image_caption="0.6-GenerativeModel-C10.pdf 第 65 页",
        ),
        img_q(
            "根据图中的时间线，若把 2014 年视为一个分界点，哪项对其后研究演进的概括最准确？",
            "生成模型不再围绕单一路线推进，而是先后出现了对抗式、自回归/流式以及扩散式等多条代表性路线并行发展。",
            [
                "2014 年以后主流方法几乎全部停止更新，时间线后半段只是早期方法的重复罗列。",
                "2014 年后的重要进展都集中在同一类自编码器框架中，方法范式没有明显变化。",
                "时间线表明生成模型研究在 2014 年后让位于分类模型，因此不再出现新的代表方法。",
            ],
            "这题不能只抄某个年份。要看完整条时间线在 2014 年之后呈现出的“多路线并行演进”这一结构性变化。",
            ["diffusion model", "timeline", "generative model"],
            ["diffusion model", "timeline"],
            image_source="Week10/0.6-GenerativeModel-C10.pdf",
            image_page=7,
            image_caption="0.6-GenerativeModel-C10.pdf 第 7 页",
        ),
        img_q(
            "若把图中的时间线误读成“后出现的方法一定完全替代先出现的方法”，最容易忽略哪一事实？",
            "时间线展示的是代表方法不断扩展和并行发展，而不是所有旧路线在新路线出现后立刻失去研究价值。",
            [
                "时间线说明 2014 年之后只剩下 GAN，一切其他生成方法都不再重要。",
                "时间线说明所有方法都属于同一种模型，只是论文年份不同。",
                "时间线说明生成模型在 2020 年后停止发展，因此不存在后续新方向。",
            ],
            "要答对这题，必须真的看时间线的整体结构。它体现的是路线扩展，而不是简单的单线替代关系。",
            ["diffusion model", "timeline", "generative model"],
            ["diffusion model", "timeline"],
            image_source="Week10/0.6-GenerativeModel-C10.pdf",
            image_page=7,
            image_caption="0.6-GenerativeModel-C10.pdf 第 7 页",
        ),
    ],
    "正则化与优化": [
        q(
            "Dropout 在训练阶段被引入，主要是为了解决什么问题？",
            "降低神经元之间的过度共适应，从而缓解过拟合。",
            [
                "让每一层输出尽量固定不变，减少网络波动。",
                "把前馈网络自动改造成循环网络，提高记忆能力。",
                "保证训练误差一定高于测试误差，从而提升泛化。",
            ],
            "Dropout 的核心不是简单“删点”，而是通过随机失活提高模型泛化能力。",
            ["dropout", "regularization", "overfitting"],
        ),
        q(
            "如果训练误差还在降，但验证误差已经开始回升，这通常说明什么？",
            "模型开始过拟合训练集。",
            [
                "模型明显欠拟合，应先继续降低模型容量。",
                "说明标签没有继续参与训练，因此误差曲线失去意义。",
                "说明模型已经自动获得最优泛化，一般无需再调参。",
            ],
            "训练好、泛化差是过拟合的典型信号，也是学习报告应重点提示的现象。",
            ["overfitting", "training error", "validation error"],
        ),
        q(
            "提前终止（early stopping）最直接依赖哪类信息来决定何时停下？",
            "验证集性能随训练轮数变化的趋势。",
            [
                "训练集文件名的排列顺序。",
                "GPU 显存占用在某个时刻达到的峰值。",
                "第一轮训练时卷积核参数的初始化大小。",
            ],
            "提前终止并不是“提早结束就更好”，而是借助验证集寻找泛化更优的停点。",
            ["early stopping", "validation set", "generalization"],
        ),
        q(
            "在目标函数里加入参数范数惩罚项，最直接是想达到什么效果？",
            "约束参数规模，降低模型过于复杂带来的过拟合风险。",
            [
                "让模型不再依赖训练数据，也能直接得到可用结果。",
                "强制所有参数收缩到 0，因此模型会自动停止学习。",
                "把原本的监督分类任务自动改写成无监督聚类任务。",
            ],
            "参数范数正则化的核心思想，是在拟合训练数据之外，对模型复杂度再施加额外约束。",
            ["regularization", "weight decay", "parameter norm"],
        ),
        img_q(
            "根据图中训练集、验证集和测试集的职责划分，若研究组每轮都先看测试集结果再决定是否换结构，被破坏的核心前提是？",
            "测试集作为最终独立评估基准的无偏性被破坏，因为模型选择过程已经反复利用了测试信息。",
            [
                "训练集将失去拟合参数的功能，因此模型无法继续更新权重。",
                "验证集会自动转化为训练集的一部分，因此不能再做超参数选择。",
                "测试集会因为被查看多次而失去标签，只能继续用于无监督训练。",
            ],
            "这道题不是在考一句口号，而是要求根据图中的三类数据职责，判断为什么“反复看测试集”会破坏最终评估的统计前提。",
            ["validation set", "training set", "test set"],
            ["validation set", "training set", "test set"],
            image_source="Week11/0.7-RegularizationOptimization-C11.pdf",
            image_page=7,
            image_caption="0.7-RegularizationOptimization-C11.pdf 第 7 页",
        ),
        img_q(
            "若一篇论文声称“训练集拟合参数、测试集挑结构、验证集最后报告结果”，根据图中的职责划分，最明显的错误是什么？",
            "把验证集和测试集的角色对调了：测试集不应参与结构选择，而验证集才用于调参和初步比较。",
            [
                "把训练集和验证集对调了，因为训练集只能用于最终一次性评估。",
                "没有错误，只要三个集合都用到了，顺序可以任意更换。",
                "错误在于验证集不应出现，深度学习只需要训练集和测试集即可。",
            ],
            "这题要求真正读懂图中三类数据集的职责，而不是只记住名词。角色一旦对调，评估逻辑就会失真。",
            ["validation set", "training set", "test set"],
            ["validation set", "training set", "test set"],
            image_source="Week11/0.7-RegularizationOptimization-C11.pdf",
            image_page=7,
            image_caption="0.7-RegularizationOptimization-C11.pdf 第 7 页",
        ),
    ],
    "深度学习开发平台": [
        q(
            "比较不同深度学习框架时，下列哪一项是更值得优先关注的？",
            "不同框架在建模、调试、部署和生态上的取舍。",
            [
                "确认所有框架内部实现完全一样，因此选型没有实际差别。",
                "只有把所有框架底层源码都读完，才有资格开始训练模型。",
                "深度学习训练只能依赖某一个商业平台，其他框架都只是包装。",
            ],
            "平台章节最重要的不是背名字，而是知道什么场景下该选什么工具。",
            ["deep learning framework", "platform", "pytorch", "tensorflow"],
        ),
        q(
            "关于 PyTorch 的特点，下列说法正确的是？",
            "更强调灵活建模和研究原型开发，便于调试和实验。",
            [
                "主要面向固定静态图部署，对研究迭代并不友好。",
                "由于不支持自动求导，所以往往需要手工推导梯度。",
                "它更适合树模型和传统机器学习，不适合神经网络实验。",
            ],
            "PyTorch 常被视为适合研究原型开发和快速实验迭代的框架。",
            ["pytorch", "dynamic graph", "research prototype"],
        ),
        q(
            "TensorFlow 2.0 相比早期版本，一个重要变化是什么？",
            "它相比早期版本更强调易用性，并与 Keras 风格结合得更紧密。",
            [
                "它彻底取消了自动微分，因此训练需要手工写梯度。",
                "它只能在 CPU 上运行，不能再利用 GPU 加速。",
                "它不再以神经网络训练为核心，而主要用于数据清洗流程。",
            ],
            "TensorFlow 2.0 更强调易用性，并提供了更统一的高层接口与更直观的编程方式。",
            ["tensorflow 2.0", "keras", "framework"],
        ),
        img_q(
            "根据图中列出的“移除 Session、强化 tf.keras、tf.function、自动初始化”等变化，TensorFlow 2.0 的改版目标最接近哪一项？",
            "把原本偏图执行、偏工程化的使用门槛，改成更接近直接编写并立即运行的开发体验。",
            [
                "把深度学习框架改造成只适合随机森林与 SVM 的传统机器学习平台。",
                "进一步强化手写静态图和底层执行细节，让开发者必须显式控制每一步图构建。",
                "弱化高层接口，要求用户在训练前手动完成所有变量和会话管理。",
            ],
            "正确答案要同时利用图中的多条改动，而不是单独盯着某一个术语。它们共同指向的是“降低使用和实验门槛”这一目标。",
            ["tensorflow 2.0", "session", "keras"],
            ["tensorflow 2.0", "session"],
            image_source="Week13/0.8-DeepLearning-tools-C13_modified.pdf",
            image_page=18,
            image_caption="0.8-DeepLearning-tools-C13_modified.pdf 第 18 页",
        ),
        img_q(
            "根据图中对 PyTorch 的描述，若课程实验需要频繁插入打印、单步定位和快速查错，优先选它的核心理由是？",
            "程序执行路径更贴近代码书写顺序，调试时更容易把错误与具体计算过程对应起来。",
            [
                "它会自动隐藏底层执行细节，因此最适合完全不看中间状态地黑箱训练。",
                "它要求先构造复杂 Session 再统一运行，因此更方便把错误集中到最后一步。",
                "它主要面向固定部署流程，研究阶段频繁改结构反而不适合使用。",
            ],
            "答题要利用图中对“线性、直观、易于使用”和“代码更简洁直观”的描述，判断其真正受益最大的场景是调试与原型实验。",
            ["pytorch", "design philosophy", "debugging"],
            ["pytorch", "design philosophy"],
            image_source="Week13/0.8-DeepLearning-tools-C13_modified.pdf",
            image_page=50,
            image_caption="0.8-DeepLearning-tools-C13_modified.pdf 第 50 页",
        ),
        img_q(
            "若课程要求学生先快速完成原型试验、再逐步理解底层实现，图中哪套框架描述更直接支持这一教学安排？",
            "更支持 PyTorch，因为图中强调它的代码直观、易读、便于查错，更适合原型实验和教学入门。",
            [
                "更支持早期 TensorFlow 的 Session/图执行方式，因为它更依赖显式底层控制，最适合初学者快速试错。",
                "两者完全等价，因为图中说明框架差异只体现在论文年份，不影响开发体验。",
                "更支持随机森林工具链，因为原型实验主要依赖多数投票而不是神经网络调试。",
            ],
            "这题要结合图中对 PyTorch 使用体验的整段描述来判断适用场景，而不是把“友好”二字当成泛泛宣传语。",
            ["pytorch", "design philosophy", "debugging"],
            ["pytorch", "design philosophy"],
            image_source="Week13/0.8-DeepLearning-tools-C13_modified.pdf",
            image_page=50,
            image_caption="0.8-DeepLearning-tools-C13_modified.pdf 第 50 页",
        ),
    ],
    "决策树、随机森林与 DeepForest": [
        q(
            "随机森林最核心的方法思想，下面哪一项概括得更准确？",
            "通过构建多棵具有随机性的决策树，再进行集成决策。",
            [
                "只训练一棵极深的决策树，然后把它当作最终模型固定下来。",
                "把卷积层和注意力层叠在一起，形成单一的混合神经网络。",
                "主要依靠手工规则判断，不依赖训练数据中的统计规律。",
            ],
            "随机森林的关键不是“树多”，而是“多棵有差异的树 + 集成”。",
            ["random forest", "ensemble learning", "decision tree"],
        ),
        q(
            "随机森林训练每棵树时，常见的随机性主要来自哪两部分？",
            "样本的随机重采样，以及划分时特征子集的随机选择。",
            [
                "把标签随机打乱，再把学习率随机设为 0。",
                "随机翻转卷积核，再随机删除位置编码。",
                "只随机初始化输出层参数，其余结构全部固定不变。",
            ],
            "样本随机性和特征随机性共同帮助随机森林提升多样性，减少过拟合。",
            ["bootstrap", "feature subset", "random forest"],
        ),
        q(
            "随机森林对一个新样本做分类时，最常见的集成决策方式是什么？",
            "由多棵树分别给出结果，再通过多数投票形成最终分类。",
            [
                "只采用第一棵树的输出，其余树主要用来做可视化说明。",
                "把所有树的节点参数直接逐项相加，再映射成类别。",
                "先训练一个判别器判断哪棵树更真实，再采用那棵树的结果。",
            ],
            "多数投票是随机森林在分类问题中的标准集成方式之一。",
            ["random forest", "majority voting", "classification"],
        ),
        q(
            "DeepForest 这类方法的提出，最能帮助学生理解哪一点？",
            "并不是所有层次化学习思路都必须依赖神经网络，树模型也可以构造多层级集成结构。",
            [
                "DeepForest 和随机森林没有方法上的关联，只是名字碰巧相似。",
                "DeepForest 的关键做法是把所有树节点替换成 LSTM 单元。",
                "DeepForest 的出现意味着以后不再需要任何集成学习方法。",
            ],
            "DeepForest 的教学价值在于帮助学生把“深层结构”和“神经网络”这两个概念区分开。",
            ["deepforest", "random forest", "ensemble learning"],
        ),
        img_q(
            "根据图中“上半部分建树、下半部分投票预测”的两段流程，若只保留下半部分而去掉上半部分的随机化设计，最可能损失的是什么？",
            "树与树之间的差异性不足，集成带来的降方差效果会明显下降。",
            [
                "每棵树都会自动退化成循环网络，因此无法继续处理表格特征。",
                "多数投票会被强制替换成 softmax，因此随机森林不再输出离散类别。",
                "所有决策树的深度都会被固定为 1，因此模型只能做线性判别。",
            ],
            "图里把“随机采样建树”和“多数投票预测”明确分成两段。真正提供集成收益的是上半部分的随机化，而不只是下半部分的投票动作。",
            ["random forest", "majority voting", "decision tree"],
            ["random forest", "majority voting"],
            image_source="Week11/DeepForest-C11.pdf",
            image_page=4,
            image_caption="DeepForest-C11.pdf 第 4 页",
        ),
        img_q(
            "若保留图中上半部分的随机采样建树，但预测时不再采用下半部分的多数投票，而只随机选一棵树输出，最先失去的是什么？",
            "集成决策带来的稳定性，因为随机森林的最终优势并不来自某一棵树，而来自多棵树的综合判断。",
            [
                "随机特征选择能力，因为投票阶段决定了每棵树如何挑选特征。",
                "训练阶段的重采样能力，因为多数投票会反向影响建树数据分布。",
                "决策树本身的分裂能力，因为没有投票时树节点无法继续做划分。",
            ],
            "图里上、下两部分分别对应“制造差异”和“聚合差异”。若去掉投票，训练随机性还在，但集成结果的稳定性会直接打折。",
            ["random forest", "majority voting", "decision tree"],
            ["random forest", "majority voting"],
            image_source="Week11/DeepForest-C11.pdf",
            image_page=4,
            image_caption="DeepForest-C11.pdf 第 4 页",
        ),
    ],
}
